server:
  port: 8190
  servlet:
    context-path: /life-from-kitchen

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/lifefromkitchen
    username: postgres
    password: postgres108
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  mvc:
    hiddenmethod:
      filter:
        enabled: true

  flyway:
    schemas: public
    baseline-on-migrate: true
    enabled: true

    baseline-description: "init"
    baseline-version: 0
